/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AaveInput {
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
    #[serde(rename = "input", skip_serializing_if = "Option::is_none")]
    pub input: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(rename = "nonce", skip_serializing_if = "Option::is_none")]
    pub nonce: Option<String>,
    #[serde(rename = "gas", skip_serializing_if = "Option::is_none")]
    pub gas: Option<String>,
    #[serde(rename = "gasPrice", skip_serializing_if = "Option::is_none")]
    pub gas_price: Option<String>,
    #[serde(rename = "chain_id", skip_serializing_if = "Option::is_none")]
    pub chain_id: Option<String>,
    #[serde(rename = "encoding", skip_serializing_if = "Option::is_none")]
    pub encoding: Option<String>,
    #[serde(rename = "EOA", skip_serializing_if = "Option::is_none")]
    pub eoa: Option<bool>,
    #[serde(rename = "contract_address", skip_serializing_if = "Option::is_none")]
    pub contract_address: Option<String>,
    #[serde(rename = "token_id", skip_serializing_if = "Option::is_none")]
    pub token_id: Option<String>,
    #[serde(rename = "token_ids", skip_serializing_if = "Option::is_none")]
    pub token_ids: Option<String>,
    #[serde(rename = "approved", skip_serializing_if = "Option::is_none")]
    pub approved: Option<bool>,
    #[serde(rename = "broadcast", skip_serializing_if = "Option::is_none")]
    pub broadcast: Option<bool>,
    #[serde(rename = "lending_pool", skip_serializing_if = "Option::is_none")]
    pub lending_pool: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    #[serde(rename = "atoken_to_redeeem", skip_serializing_if = "Option::is_none")]
    pub atoken_to_redeeem: Option<String>,
    #[serde(rename = "ref_code", skip_serializing_if = "Option::is_none")]
    pub ref_code: Option<String>,
    #[serde(rename = "interest_rate_mode", skip_serializing_if = "Option::is_none")]
    pub interest_rate_mode: Option<String>,
}

impl AaveInput {
    pub fn new() -> AaveInput {
        AaveInput {
            to: None,
            data: None,
            input: None,
            value: None,
            nonce: None,
            gas: None,
            gas_price: None,
            chain_id: None,
            encoding: None,
            eoa: None,
            contract_address: None,
            token_id: None,
            token_ids: None,
            approved: None,
            broadcast: None,
            lending_pool: None,
            amount: None,
            atoken_to_redeeem: None,
            ref_code: None,
            interest_rate_mode: None,
        }
    }
}


