/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AvailablePaymentMethod {
    #[serde(rename = "icon")]
    pub icon: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "paymentTypeId")]
    pub payment_type_id: String,
}

impl AvailablePaymentMethod {
    pub fn new(icon: String, name: String, payment_type_id: String) -> AvailablePaymentMethod {
        AvailablePaymentMethod {
            icon,
            name,
            payment_type_id,
        }
    }
}


