/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Quote {
    #[serde(rename = "recommendations")]
    pub recommendations: Vec<String>,
    #[serde(rename = "paymentMethod")]
    pub payment_method: String,
    #[serde(rename = "quoteId")]
    pub quote_id: String,
    #[serde(rename = "ramp")]
    pub ramp: String,
    #[serde(rename = "availablePaymentMethods")]
    pub available_payment_methods: Vec<crate::models::AvailablePaymentMethod>,
    #[serde(rename = "payout")]
    pub payout: f64,
    #[serde(rename = "transactionFee")]
    pub transaction_fee: f64,
    #[serde(rename = "networkFee")]
    pub network_fee: f64,
    #[serde(rename = "rate")]
    pub rate: f64,
}

impl Quote {
    pub fn new(recommendations: Vec<String>, payment_method: String, quote_id: String, ramp: String, available_payment_methods: Vec<crate::models::AvailablePaymentMethod>, payout: f64, transaction_fee: f64, network_fee: f64, rate: f64) -> Quote {
        Quote {
            recommendations,
            payment_method,
            quote_id,
            ramp,
            available_payment_methods,
            payout,
            transaction_fee,
            network_fee,
            rate,
        }
    }
}


